# Generated by Django 6.0.7 on 2026-08-04 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_options_conversationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstatus',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='chat.conversation'),
        ),
    ]
